
export const GET_CART_PRODUCT_SUCCESS = "GET_CART_PRODUCT_SUCCESS";
export const GET_CART_PRODUCT_REQUEST = "GET_CART_PRODUCT_REQUEST";
export const GET_CART_PRODUCT_FAILURE = "GET_CART_PRODUCT_FAILURE";

export const POST_CART_PRODUCT_SUCCESS = "POST_CART_PRODUCT_SUCCESS";
export const POST_CART_PRODUCT_REQUEST = "POST_CART_PRODUCT_REQUEST";
export const POST_CART_PRODUCT_FAILURE = "POST_CART_PRODUCT_FAILURE";